### ISSUE TITLE
Leading spaces in package names from TOC can cause errors

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#1]
Reprex:

```r
groundhogR::groundhog.library("dplyr", "2020-02-01", ignore.package.conflicts = TRUE)
```

**Comment by urisohn** [comment]
Fixed.
Deleted all spaces in existing .csv files and modified the script that updates those files to that they will not be added in the future.

**Comment by Bisaloo** [comment]
Re-opening since this is apparently still an issue. Reproducible example:

```r
groundhog.library("lightr", "2020-04-05")
```

**Comment by urisohn** [comment]
You mean your cran.toc.csv file has a space for lightr?
Just downloaded the csv file from the server and pened it in notepad, looks like this:
![image](https://user-images.githubusercontent.com/56013245/79039177-c28a7a00-7bdf-11ea-8d8e-5cc902e07672.png)

**Comment by urisohn** [comment]
no space. could something else be triggering it?

**Comment by Bisaloo** [comment]
sorry, here's the full reproducible example with the output:

``` r
library(groundhogR)

toc("lightr", dependencies = TRUE)
#>      Version  Published                       Imports Depends
#> 6359     0.1 2019-11-19                pbmcapply,xml2        
#> 3651     1.0 2020-01-27   future.apply,progressr,xml2        
#> 337      1.1 2020-04-01 future.apply, progressr, xml2       R
#>                                        Suggests
#> 6359     knitr,pavo,rmarkdown,spelling,testthat
#> 3651     knitr,pavo,rmarkdown,spelling,testthat
#> 337  knitr, pavo, rmarkdown, spelling, testthat

groundhog.library("lightr", "2020-04-05")
#> [1;36mgroundhog.library() says [using R-3.6.1]:[0m
#> [36mThere is no package ' progressr' in our database of all CRAN packages ever posted.
#>    Keep in mind that:
#>     1. package names are cAsE seNsiTive
#>     2. The package name needs to be in quotes: e.g., toc('groundhogR') 
#>     3. Only CRAN packages can be loaded via groundhogR[0m
#> Error in toc(pkg):
```

<sup>Created on 2020-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


As you can see, in the `Suggests` column, it's strange because for 1.0, the package and separated by `,` and for 1.1, by `, `, which is the source of the error I suspect.

**Comment by urisohn** [comment]
I had added a function to kill spaces but was not being called. Should be resolved now, the files on the servers should already have the spaces removed
